import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  // coding
  ReactNativeSidebar: [{ type: 'autogenerated', dirName: 'coding/react-native' }],
  UniappSidebar: [{ type: 'autogenerated', dirName: 'coding/uniapp' }],
  VueSidebar: [{ type: 'autogenerated', dirName: 'coding/vue' }],

  // dev-tools
  DocusaurusSidebar: [{ type: 'autogenerated', dirName: 'dev-tools/docusaurus' }],
  GitSidebar: [{ type: 'autogenerated', dirName: 'dev-tools/git' }],
  DockerSidebar: [{ type: 'autogenerated', dirName: 'dev-tools/docker' }],
  PackageManageSidebar: [{ type: 'autogenerated', dirName: 'dev-tools/package-manage' }],
  ServerSidebar: [{ type: 'autogenerated', dirName: 'dev-tools/server' }],
  AgentSidebar: [{ type: 'autogenerated', dirName: 'dev-tools/agent' }],
  // database
  PostgreSQLSidebar: [{ type: 'autogenerated', dirName: 'database/postgresql' }],
  SqlServerSidebar: [{ type: 'autogenerated', dirName: 'database/sqlserver' }],
}

export default sidebars
